// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Home.h"
#include "ui_Recipe_Selection.h"
#include "ui_Customisation.h"
#include "ui_Cooking.h"
#include "ui_ChkIngredients.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1570860662);    // assets/icons/chef-hat-white.png
LV_IMG_DECLARE(ui_img_vitxmitatronics_png);    // assets/VITxMitatronics.png
LV_IMG_DECLARE(ui_img_799859158);    // assets/icons/wi-fi.png
LV_IMG_DECLARE(ui_img_387274184);    // assets/Recipe Image/masoor-dal.png
LV_IMG_DECLARE(ui_img_39411831);    // assets/Recipe Image/spinach-soup.png
LV_IMG_DECLARE(ui_img_162746961);    // assets/Recipe Image/tomato-soup.png
LV_IMG_DECLARE(ui_img_190461950);    // assets/Recipe Image/tur-dal.png
LV_IMG_DECLARE(ui_img_icons_warning_png);    // assets/icons/warning.png
LV_IMG_DECLARE(ui_img_icons_spices_png);    // assets/icons/spices.png
LV_IMG_DECLARE(ui_img_icons_drop_png);    // assets/icons/drop.png
LV_IMG_DECLARE(ui_img_icons_tomato_png);    // assets/icons/tomato.png
LV_IMG_DECLARE(ui_img_icons_onion_png);    // assets/icons/onion.png
LV_IMG_DECLARE(ui_img_icons_spinach_png);    // assets/icons/spinach.png
LV_IMG_DECLARE(ui_img_icons_garlic_png);    // assets/icons/garlic.png

// FONTS
LV_FONT_DECLARE(ui_font_Roboto_balck_20);
LV_FONT_DECLARE(ui_font_Roboto_black_26);
LV_FONT_DECLARE(ui_font_Roboto_boldcondensed_25);
LV_FONT_DECLARE(ui_font_Roboto_bold_30);
LV_FONT_DECLARE(ui_font_Roboto_bold_50);
LV_FONT_DECLARE(ui_font_Roboto_condensed_16);
LV_FONT_DECLARE(ui_font_Roboto_condensed_25);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
