// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_ChkIngredients = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_BackToHome = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Status = NULL;
lv_obj_t * ui_Cumin = NULL;
lv_obj_t * ui_CuminBar = NULL;
lv_obj_t * ui_WarningCumin = NULL;
lv_obj_t * ui_CuminIcon = NULL;
lv_obj_t * ui_CuminLabel = NULL;
lv_obj_t * ui_Salt = NULL;
lv_obj_t * ui_SaltBar = NULL;
lv_obj_t * ui_WarningSalt = NULL;
lv_obj_t * ui_SaltIcon2 = NULL;
lv_obj_t * ui_SaltLabel = NULL;
lv_obj_t * ui_Turmeric = NULL;
lv_obj_t * ui_TurmericBar = NULL;
lv_obj_t * ui_WarningTurmeric = NULL;
lv_obj_t * ui_TurmericIcon = NULL;
lv_obj_t * ui_TurmericLabel = NULL;
lv_obj_t * ui_Mustard = NULL;
lv_obj_t * ui_MustardBar = NULL;
lv_obj_t * ui_WarningMustard = NULL;
lv_obj_t * ui_MustardIcon = NULL;
lv_obj_t * ui_MustardLabel = NULL;
lv_obj_t * ui_Pepper = NULL;
lv_obj_t * ui_PepperBar = NULL;
lv_obj_t * ui_WarningPepper = NULL;
lv_obj_t * ui_PepperIcon = NULL;
lv_obj_t * ui_PepperLabel2 = NULL;
lv_obj_t * ui_Water = NULL;
lv_obj_t * ui_WaterBar = NULL;
lv_obj_t * ui_WarningWater = NULL;
lv_obj_t * ui_WaterIcon = NULL;
lv_obj_t * ui_WaterLabel = NULL;
lv_obj_t * ui_Oil = NULL;
lv_obj_t * ui_OilBar = NULL;
lv_obj_t * ui_WarningOil = NULL;
lv_obj_t * ui_OilIcon = NULL;
lv_obj_t * ui_OilLabel = NULL;
lv_obj_t * ui_Tomato = NULL;
lv_obj_t * ui_TomatoBar = NULL;
lv_obj_t * ui_WarningTomato = NULL;
lv_obj_t * ui_TomatoIcon = NULL;
lv_obj_t * ui_TomatoLabel = NULL;
lv_obj_t * ui_Onion = NULL;
lv_obj_t * ui_OnionBar = NULL;
lv_obj_t * ui_WarningOnion = NULL;
lv_obj_t * ui_OnionIcon = NULL;
lv_obj_t * ui_OnionLabel = NULL;
lv_obj_t * ui_Spinach = NULL;
lv_obj_t * ui_SpinachBar = NULL;
lv_obj_t * ui_WarningSpinach = NULL;
lv_obj_t * ui_SpinachIcon = NULL;
lv_obj_t * ui_SpinachLabel = NULL;
lv_obj_t * ui_Garlic = NULL;
lv_obj_t * ui_GarlicBar = NULL;
lv_obj_t * ui_WarningGarlic = NULL;
lv_obj_t * ui_GarlicIcon = NULL;
lv_obj_t * ui_GarlicLabel = NULL;
// event funtions
void ui_event_ChkIngredients(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        IngredientBarSetup(e);
    }
}

void ui_event_BackToHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Home_screen_init);
    }
}

// build funtions

void ui_ChkIngredients_screen_init(void)
{
    ui_ChkIngredients = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ChkIngredients, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_ChkIngredients);
    lv_img_set_src(ui_Image9, &ui_img_vitxmitatronics_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_Image9, 5);
    lv_obj_set_y(ui_Image9, -175);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackToHome = lv_btn_create(ui_ChkIngredients);
    lv_obj_set_width(ui_BackToHome, 49);
    lv_obj_set_height(ui_BackToHome, 23);
    lv_obj_set_x(ui_BackToHome, 350);
    lv_obj_set_y(ui_BackToHome, 209);
    lv_obj_set_align(ui_BackToHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackToHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackToHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackToHome, lv_color_hex(0xE65062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackToHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_BackToHome);
    lv_obj_set_width(ui_Label15, 33);
    lv_obj_set_height(ui_Label15, 14);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Back");
    lv_obj_set_style_text_align(ui_Label15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Roboto_condensed_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Status = lv_obj_create(ui_ChkIngredients);
    lv_obj_remove_style_all(ui_Status);
    lv_obj_set_width(ui_Status, 619);
    lv_obj_set_height(ui_Status, 299);
    lv_obj_set_x(ui_Status, 2);
    lv_obj_set_y(ui_Status, 35);
    lv_obj_set_align(ui_Status, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Status, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Status, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Status, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Status, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Status, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Status, lv_color_hex(0x2A2929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Status, lv_color_hex(0x878686), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Status, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Status, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Status, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Status, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Status, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Status, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cumin = lv_obj_create(ui_Status);
    lv_obj_set_width(ui_Cumin, 606);
    lv_obj_set_height(ui_Cumin, 50);
    lv_obj_set_x(ui_Cumin, 39);
    lv_obj_set_y(ui_Cumin, 4);
    lv_obj_set_align(ui_Cumin, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Cumin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CuminBar = lv_bar_create(ui_Cumin);
    lv_bar_set_value(ui_CuminBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_CuminBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_CuminBar, 464);
    lv_obj_set_height(ui_CuminBar, 10);
    lv_obj_set_x(ui_CuminBar, 21);
    lv_obj_set_y(ui_CuminBar, -1);
    lv_obj_set_align(ui_CuminBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_CuminBar, lv_color_hex(0x732C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CuminBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CuminBar, lv_color_hex(0xE65062), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CuminBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WarningCumin = lv_img_create(ui_Cumin);
    lv_img_set_src(ui_WarningCumin, &ui_img_icons_warning_png);
    lv_obj_set_x(ui_WarningCumin, 270);
    lv_obj_set_y(ui_WarningCumin, -1);
    lv_obj_set_align(ui_WarningCumin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningCumin, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WarningCumin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WarningCumin, 20);

    ui_CuminIcon = lv_img_create(ui_Cumin);
    lv_img_set_src(ui_CuminIcon, &ui_img_icons_spices_png);
    lv_obj_set_width(ui_CuminIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CuminIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CuminIcon, -282);
    lv_obj_set_y(ui_CuminIcon, 0);
    lv_obj_set_align(ui_CuminIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CuminIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CuminIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_CuminIcon, 15);

    ui_CuminLabel = lv_label_create(ui_Cumin);
    lv_obj_set_width(ui_CuminLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CuminLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CuminLabel, -241);
    lv_obj_set_y(ui_CuminLabel, -1);
    lv_obj_set_align(ui_CuminLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CuminLabel, "Cumin");

    ui_Salt = lv_obj_create(ui_Status);
    lv_obj_set_width(ui_Salt, 606);
    lv_obj_set_height(ui_Salt, 50);
    lv_obj_set_x(ui_Salt, 39);
    lv_obj_set_y(ui_Salt, 4);
    lv_obj_set_align(ui_Salt, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Salt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SaltBar = lv_bar_create(ui_Salt);
    lv_bar_set_value(ui_SaltBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SaltBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SaltBar, 464);
    lv_obj_set_height(ui_SaltBar, 10);
    lv_obj_set_x(ui_SaltBar, 21);
    lv_obj_set_y(ui_SaltBar, -1);
    lv_obj_set_align(ui_SaltBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SaltBar, lv_color_hex(0x732C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SaltBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SaltBar, lv_color_hex(0xE65062), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SaltBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WarningSalt = lv_img_create(ui_Salt);
    lv_img_set_src(ui_WarningSalt, &ui_img_icons_warning_png);
    lv_obj_set_x(ui_WarningSalt, 270);
    lv_obj_set_y(ui_WarningSalt, -1);
    lv_obj_set_align(ui_WarningSalt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningSalt, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WarningSalt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WarningSalt, 20);

    ui_SaltIcon2 = lv_img_create(ui_Salt);
    lv_img_set_src(ui_SaltIcon2, &ui_img_icons_spices_png);
    lv_obj_set_width(ui_SaltIcon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaltIcon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaltIcon2, -282);
    lv_obj_set_y(ui_SaltIcon2, 0);
    lv_obj_set_align(ui_SaltIcon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaltIcon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SaltIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SaltIcon2, 15);

    ui_SaltLabel = lv_label_create(ui_Salt);
    lv_obj_set_width(ui_SaltLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaltLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaltLabel, -241);
    lv_obj_set_y(ui_SaltLabel, -1);
    lv_obj_set_align(ui_SaltLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaltLabel, "Salt");

    ui_Turmeric = lv_obj_create(ui_Status);
    lv_obj_set_width(ui_Turmeric, 606);
    lv_obj_set_height(ui_Turmeric, 50);
    lv_obj_set_x(ui_Turmeric, 39);
    lv_obj_set_y(ui_Turmeric, 4);
    lv_obj_set_align(ui_Turmeric, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Turmeric, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TurmericBar = lv_bar_create(ui_Turmeric);
    lv_bar_set_value(ui_TurmericBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_TurmericBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_TurmericBar, 464);
    lv_obj_set_height(ui_TurmericBar, 10);
    lv_obj_set_x(ui_TurmericBar, 21);
    lv_obj_set_y(ui_TurmericBar, -1);
    lv_obj_set_align(ui_TurmericBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_TurmericBar, lv_color_hex(0x732C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TurmericBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TurmericBar, lv_color_hex(0xE65062), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TurmericBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WarningTurmeric = lv_img_create(ui_Turmeric);
    lv_img_set_src(ui_WarningTurmeric, &ui_img_icons_warning_png);
    lv_obj_set_x(ui_WarningTurmeric, 270);
    lv_obj_set_y(ui_WarningTurmeric, -1);
    lv_obj_set_align(ui_WarningTurmeric, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningTurmeric, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WarningTurmeric, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WarningTurmeric, 20);

    ui_TurmericIcon = lv_img_create(ui_Turmeric);
    lv_img_set_src(ui_TurmericIcon, &ui_img_icons_spices_png);
    lv_obj_set_width(ui_TurmericIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TurmericIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TurmericIcon, -282);
    lv_obj_set_y(ui_TurmericIcon, 0);
    lv_obj_set_align(ui_TurmericIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TurmericIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TurmericIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_TurmericIcon, 15);

    ui_TurmericLabel = lv_label_create(ui_Turmeric);
    lv_obj_set_width(ui_TurmericLabel, 49);
    lv_obj_set_height(ui_TurmericLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TurmericLabel, -241);
    lv_obj_set_y(ui_TurmericLabel, -1);
    lv_obj_set_align(ui_TurmericLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_TurmericLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_TurmericLabel, "Turmeric");

    ui_Mustard = lv_obj_create(ui_Status);
    lv_obj_set_width(ui_Mustard, 606);
    lv_obj_set_height(ui_Mustard, 50);
    lv_obj_set_x(ui_Mustard, 39);
    lv_obj_set_y(ui_Mustard, 4);
    lv_obj_set_align(ui_Mustard, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Mustard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MustardBar = lv_bar_create(ui_Mustard);
    lv_bar_set_value(ui_MustardBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_MustardBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_MustardBar, 464);
    lv_obj_set_height(ui_MustardBar, 10);
    lv_obj_set_x(ui_MustardBar, 21);
    lv_obj_set_y(ui_MustardBar, -1);
    lv_obj_set_align(ui_MustardBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_MustardBar, lv_color_hex(0x732C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MustardBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MustardBar, lv_color_hex(0xE65062), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MustardBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WarningMustard = lv_img_create(ui_Mustard);
    lv_img_set_src(ui_WarningMustard, &ui_img_icons_warning_png);
    lv_obj_set_x(ui_WarningMustard, 270);
    lv_obj_set_y(ui_WarningMustard, -1);
    lv_obj_set_align(ui_WarningMustard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningMustard, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WarningMustard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WarningMustard, 20);

    ui_MustardIcon = lv_img_create(ui_Mustard);
    lv_img_set_src(ui_MustardIcon, &ui_img_icons_spices_png);
    lv_obj_set_width(ui_MustardIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MustardIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MustardIcon, -282);
    lv_obj_set_y(ui_MustardIcon, 0);
    lv_obj_set_align(ui_MustardIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MustardIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MustardIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_MustardIcon, 15);

    ui_MustardLabel = lv_label_create(ui_Mustard);
    lv_obj_set_width(ui_MustardLabel, 50);
    lv_obj_set_height(ui_MustardLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MustardLabel, -241);
    lv_obj_set_y(ui_MustardLabel, -1);
    lv_obj_set_align(ui_MustardLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_MustardLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_MustardLabel, "Mustard");

    ui_Pepper = lv_obj_create(ui_Status);
    lv_obj_set_width(ui_Pepper, 606);
    lv_obj_set_height(ui_Pepper, 50);
    lv_obj_set_x(ui_Pepper, 39);
    lv_obj_set_y(ui_Pepper, 4);
    lv_obj_set_align(ui_Pepper, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Pepper, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PepperBar = lv_bar_create(ui_Pepper);
    lv_bar_set_value(ui_PepperBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_PepperBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_PepperBar, 464);
    lv_obj_set_height(ui_PepperBar, 10);
    lv_obj_set_x(ui_PepperBar, 21);
    lv_obj_set_y(ui_PepperBar, -1);
    lv_obj_set_align(ui_PepperBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_PepperBar, lv_color_hex(0x732C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PepperBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PepperBar, lv_color_hex(0xE65062), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PepperBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WarningPepper = lv_img_create(ui_Pepper);
    lv_img_set_src(ui_WarningPepper, &ui_img_icons_warning_png);
    lv_obj_set_x(ui_WarningPepper, 270);
    lv_obj_set_y(ui_WarningPepper, -1);
    lv_obj_set_align(ui_WarningPepper, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningPepper, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WarningPepper, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WarningPepper, 20);

    ui_PepperIcon = lv_img_create(ui_Pepper);
    lv_img_set_src(ui_PepperIcon, &ui_img_icons_spices_png);
    lv_obj_set_width(ui_PepperIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PepperIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PepperIcon, -282);
    lv_obj_set_y(ui_PepperIcon, 0);
    lv_obj_set_align(ui_PepperIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PepperIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PepperIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PepperIcon, 15);

    ui_PepperLabel2 = lv_label_create(ui_Pepper);
    lv_obj_set_width(ui_PepperLabel2, 50);
    lv_obj_set_height(ui_PepperLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PepperLabel2, -241);
    lv_obj_set_y(ui_PepperLabel2, -1);
    lv_obj_set_align(ui_PepperLabel2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_PepperLabel2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_PepperLabel2, "Pepper");

    ui_Water = lv_obj_create(ui_Status);
    lv_obj_set_width(ui_Water, 606);
    lv_obj_set_height(ui_Water, 50);
    lv_obj_set_x(ui_Water, 39);
    lv_obj_set_y(ui_Water, 4);
    lv_obj_set_align(ui_Water, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Water, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WaterBar = lv_bar_create(ui_Water);
    lv_bar_set_value(ui_WaterBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_WaterBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_WaterBar, 464);
    lv_obj_set_height(ui_WaterBar, 10);
    lv_obj_set_x(ui_WaterBar, 21);
    lv_obj_set_y(ui_WaterBar, -1);
    lv_obj_set_align(ui_WaterBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_WaterBar, lv_color_hex(0x732C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WaterBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WaterBar, lv_color_hex(0xE65062), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WaterBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WarningWater = lv_img_create(ui_Water);
    lv_img_set_src(ui_WarningWater, &ui_img_icons_warning_png);
    lv_obj_set_x(ui_WarningWater, 270);
    lv_obj_set_y(ui_WarningWater, -1);
    lv_obj_set_align(ui_WarningWater, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningWater, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WarningWater, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WarningWater, 20);

    ui_WaterIcon = lv_img_create(ui_Water);
    lv_img_set_src(ui_WaterIcon, &ui_img_icons_drop_png);
    lv_obj_set_width(ui_WaterIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WaterIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WaterIcon, -282);
    lv_obj_set_y(ui_WaterIcon, 0);
    lv_obj_set_align(ui_WaterIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WaterIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WaterIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WaterIcon, 15);

    ui_WaterLabel = lv_label_create(ui_Water);
    lv_obj_set_width(ui_WaterLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WaterLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WaterLabel, -241);
    lv_obj_set_y(ui_WaterLabel, -1);
    lv_obj_set_align(ui_WaterLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_WaterLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_WaterLabel, "Water");

    ui_Oil = lv_obj_create(ui_Status);
    lv_obj_set_width(ui_Oil, 606);
    lv_obj_set_height(ui_Oil, 50);
    lv_obj_set_x(ui_Oil, 39);
    lv_obj_set_y(ui_Oil, 4);
    lv_obj_set_align(ui_Oil, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Oil, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OilBar = lv_bar_create(ui_Oil);
    lv_bar_set_value(ui_OilBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_OilBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_OilBar, 464);
    lv_obj_set_height(ui_OilBar, 10);
    lv_obj_set_x(ui_OilBar, 21);
    lv_obj_set_y(ui_OilBar, -1);
    lv_obj_set_align(ui_OilBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_OilBar, lv_color_hex(0x732C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OilBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_OilBar, lv_color_hex(0xE65062), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OilBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WarningOil = lv_img_create(ui_Oil);
    lv_img_set_src(ui_WarningOil, &ui_img_icons_warning_png);
    lv_obj_set_x(ui_WarningOil, 270);
    lv_obj_set_y(ui_WarningOil, -1);
    lv_obj_set_align(ui_WarningOil, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningOil, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WarningOil, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WarningOil, 20);

    ui_OilIcon = lv_img_create(ui_Oil);
    lv_img_set_src(ui_OilIcon, &ui_img_icons_drop_png);
    lv_obj_set_width(ui_OilIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OilIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OilIcon, -282);
    lv_obj_set_y(ui_OilIcon, 0);
    lv_obj_set_align(ui_OilIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OilIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OilIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_OilIcon, 15);

    ui_OilLabel = lv_label_create(ui_Oil);
    lv_obj_set_width(ui_OilLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OilLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OilLabel, -241);
    lv_obj_set_y(ui_OilLabel, -1);
    lv_obj_set_align(ui_OilLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_OilLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_OilLabel, "Oil");

    ui_Tomato = lv_obj_create(ui_Status);
    lv_obj_set_width(ui_Tomato, 606);
    lv_obj_set_height(ui_Tomato, 50);
    lv_obj_set_x(ui_Tomato, 39);
    lv_obj_set_y(ui_Tomato, 4);
    lv_obj_set_align(ui_Tomato, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tomato, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TomatoBar = lv_bar_create(ui_Tomato);
    lv_bar_set_value(ui_TomatoBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_TomatoBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_TomatoBar, 464);
    lv_obj_set_height(ui_TomatoBar, 10);
    lv_obj_set_x(ui_TomatoBar, 21);
    lv_obj_set_y(ui_TomatoBar, -1);
    lv_obj_set_align(ui_TomatoBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_TomatoBar, lv_color_hex(0x732C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TomatoBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TomatoBar, lv_color_hex(0xE65062), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TomatoBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WarningTomato = lv_img_create(ui_Tomato);
    lv_img_set_src(ui_WarningTomato, &ui_img_icons_warning_png);
    lv_obj_set_x(ui_WarningTomato, 270);
    lv_obj_set_y(ui_WarningTomato, -1);
    lv_obj_set_align(ui_WarningTomato, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningTomato, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WarningTomato, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WarningTomato, 20);

    ui_TomatoIcon = lv_img_create(ui_Tomato);
    lv_img_set_src(ui_TomatoIcon, &ui_img_icons_tomato_png);
    lv_obj_set_width(ui_TomatoIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TomatoIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TomatoIcon, -282);
    lv_obj_set_y(ui_TomatoIcon, 0);
    lv_obj_set_align(ui_TomatoIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TomatoIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TomatoIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_TomatoIcon, 15);

    ui_TomatoLabel = lv_label_create(ui_Tomato);
    lv_obj_set_width(ui_TomatoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TomatoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TomatoLabel, -241);
    lv_obj_set_y(ui_TomatoLabel, -1);
    lv_obj_set_align(ui_TomatoLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_TomatoLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_TomatoLabel, "Tomato");

    ui_Onion = lv_obj_create(ui_Status);
    lv_obj_set_width(ui_Onion, 606);
    lv_obj_set_height(ui_Onion, 50);
    lv_obj_set_x(ui_Onion, 39);
    lv_obj_set_y(ui_Onion, 4);
    lv_obj_set_align(ui_Onion, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Onion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnionBar = lv_bar_create(ui_Onion);
    lv_bar_set_value(ui_OnionBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_OnionBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_OnionBar, 464);
    lv_obj_set_height(ui_OnionBar, 10);
    lv_obj_set_x(ui_OnionBar, 21);
    lv_obj_set_y(ui_OnionBar, -1);
    lv_obj_set_align(ui_OnionBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_OnionBar, lv_color_hex(0x732C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OnionBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_OnionBar, lv_color_hex(0xE65062), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OnionBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WarningOnion = lv_img_create(ui_Onion);
    lv_img_set_src(ui_WarningOnion, &ui_img_icons_warning_png);
    lv_obj_set_x(ui_WarningOnion, 270);
    lv_obj_set_y(ui_WarningOnion, -1);
    lv_obj_set_align(ui_WarningOnion, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningOnion, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WarningOnion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WarningOnion, 20);

    ui_OnionIcon = lv_img_create(ui_Onion);
    lv_img_set_src(ui_OnionIcon, &ui_img_icons_onion_png);
    lv_obj_set_width(ui_OnionIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnionIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnionIcon, -282);
    lv_obj_set_y(ui_OnionIcon, 0);
    lv_obj_set_align(ui_OnionIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OnionIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OnionIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_OnionIcon, 15);

    ui_OnionLabel = lv_label_create(ui_Onion);
    lv_obj_set_width(ui_OnionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnionLabel, -241);
    lv_obj_set_y(ui_OnionLabel, -1);
    lv_obj_set_align(ui_OnionLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_OnionLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_OnionLabel, "Onion");

    ui_Spinach = lv_obj_create(ui_Status);
    lv_obj_set_width(ui_Spinach, 606);
    lv_obj_set_height(ui_Spinach, 50);
    lv_obj_set_x(ui_Spinach, 39);
    lv_obj_set_y(ui_Spinach, 4);
    lv_obj_set_align(ui_Spinach, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinach, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpinachBar = lv_bar_create(ui_Spinach);
    lv_bar_set_value(ui_SpinachBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SpinachBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpinachBar, 464);
    lv_obj_set_height(ui_SpinachBar, 10);
    lv_obj_set_x(ui_SpinachBar, 21);
    lv_obj_set_y(ui_SpinachBar, -1);
    lv_obj_set_align(ui_SpinachBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SpinachBar, lv_color_hex(0x732C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpinachBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpinachBar, lv_color_hex(0xE65062), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpinachBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WarningSpinach = lv_img_create(ui_Spinach);
    lv_img_set_src(ui_WarningSpinach, &ui_img_icons_warning_png);
    lv_obj_set_x(ui_WarningSpinach, 270);
    lv_obj_set_y(ui_WarningSpinach, -1);
    lv_obj_set_align(ui_WarningSpinach, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningSpinach, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WarningSpinach, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WarningSpinach, 20);

    ui_SpinachIcon = lv_img_create(ui_Spinach);
    lv_img_set_src(ui_SpinachIcon, &ui_img_icons_spinach_png);
    lv_obj_set_width(ui_SpinachIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpinachIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpinachIcon, -282);
    lv_obj_set_y(ui_SpinachIcon, 0);
    lv_obj_set_align(ui_SpinachIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpinachIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SpinachIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SpinachIcon, 15);

    ui_SpinachLabel = lv_label_create(ui_Spinach);
    lv_obj_set_width(ui_SpinachLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpinachLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpinachLabel, -241);
    lv_obj_set_y(ui_SpinachLabel, -1);
    lv_obj_set_align(ui_SpinachLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_SpinachLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_SpinachLabel, "Spinach");

    ui_Garlic = lv_obj_create(ui_Status);
    lv_obj_set_width(ui_Garlic, 606);
    lv_obj_set_height(ui_Garlic, 50);
    lv_obj_set_x(ui_Garlic, 39);
    lv_obj_set_y(ui_Garlic, 4);
    lv_obj_set_align(ui_Garlic, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Garlic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GarlicBar = lv_bar_create(ui_Garlic);
    lv_bar_set_value(ui_GarlicBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_GarlicBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_GarlicBar, 464);
    lv_obj_set_height(ui_GarlicBar, 10);
    lv_obj_set_x(ui_GarlicBar, 21);
    lv_obj_set_y(ui_GarlicBar, -1);
    lv_obj_set_align(ui_GarlicBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_GarlicBar, lv_color_hex(0x732C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GarlicBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_GarlicBar, lv_color_hex(0xE65062), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GarlicBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WarningGarlic = lv_img_create(ui_Garlic);
    lv_img_set_src(ui_WarningGarlic, &ui_img_icons_warning_png);
    lv_obj_set_x(ui_WarningGarlic, 270);
    lv_obj_set_y(ui_WarningGarlic, -1);
    lv_obj_set_align(ui_WarningGarlic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WarningGarlic, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WarningGarlic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WarningGarlic, 20);

    ui_GarlicIcon = lv_img_create(ui_Garlic);
    lv_img_set_src(ui_GarlicIcon, &ui_img_icons_garlic_png);
    lv_obj_set_width(ui_GarlicIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GarlicIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GarlicIcon, -282);
    lv_obj_set_y(ui_GarlicIcon, 0);
    lv_obj_set_align(ui_GarlicIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GarlicIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GarlicIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_GarlicIcon, 15);

    ui_GarlicLabel = lv_label_create(ui_Garlic);
    lv_obj_set_width(ui_GarlicLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GarlicLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GarlicLabel, -241);
    lv_obj_set_y(ui_GarlicLabel, -1);
    lv_obj_set_align(ui_GarlicLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_GarlicLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_GarlicLabel, "Garlic");

    lv_obj_add_event_cb(ui_BackToHome, ui_event_BackToHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ChkIngredients, ui_event_ChkIngredients, LV_EVENT_ALL, NULL);

}

void ui_ChkIngredients_screen_destroy(void)
{
    if(ui_ChkIngredients) lv_obj_del(ui_ChkIngredients);

    // NULL screen variables
    ui_ChkIngredients = NULL;
    ui_Image9 = NULL;
    ui_BackToHome = NULL;
    ui_Label15 = NULL;
    ui_Status = NULL;
    ui_Cumin = NULL;
    ui_CuminBar = NULL;
    ui_WarningCumin = NULL;
    ui_CuminIcon = NULL;
    ui_CuminLabel = NULL;
    ui_Salt = NULL;
    ui_SaltBar = NULL;
    ui_WarningSalt = NULL;
    ui_SaltIcon2 = NULL;
    ui_SaltLabel = NULL;
    ui_Turmeric = NULL;
    ui_TurmericBar = NULL;
    ui_WarningTurmeric = NULL;
    ui_TurmericIcon = NULL;
    ui_TurmericLabel = NULL;
    ui_Mustard = NULL;
    ui_MustardBar = NULL;
    ui_WarningMustard = NULL;
    ui_MustardIcon = NULL;
    ui_MustardLabel = NULL;
    ui_Pepper = NULL;
    ui_PepperBar = NULL;
    ui_WarningPepper = NULL;
    ui_PepperIcon = NULL;
    ui_PepperLabel2 = NULL;
    ui_Water = NULL;
    ui_WaterBar = NULL;
    ui_WarningWater = NULL;
    ui_WaterIcon = NULL;
    ui_WaterLabel = NULL;
    ui_Oil = NULL;
    ui_OilBar = NULL;
    ui_WarningOil = NULL;
    ui_OilIcon = NULL;
    ui_OilLabel = NULL;
    ui_Tomato = NULL;
    ui_TomatoBar = NULL;
    ui_WarningTomato = NULL;
    ui_TomatoIcon = NULL;
    ui_TomatoLabel = NULL;
    ui_Onion = NULL;
    ui_OnionBar = NULL;
    ui_WarningOnion = NULL;
    ui_OnionIcon = NULL;
    ui_OnionLabel = NULL;
    ui_Spinach = NULL;
    ui_SpinachBar = NULL;
    ui_WarningSpinach = NULL;
    ui_SpinachIcon = NULL;
    ui_SpinachLabel = NULL;
    ui_Garlic = NULL;
    ui_GarlicBar = NULL;
    ui_WarningGarlic = NULL;
    ui_GarlicIcon = NULL;
    ui_GarlicLabel = NULL;

}
