// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Wifi_menu = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_ToStatusChk = NULL;
lv_obj_t * ui_Label16 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Recipe_Selection, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Recipe_Selection_screen_init);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_basic_set_property(ui_Wifi_menu, _UI_BASIC_PROPERTY_POSITION_X,  -304);
    }
}

void ui_event_ToStatusChk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ChkIngredients, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ChkIngredients_screen_init);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Home);
    lv_img_set_src(ui_Image2, &ui_img_1570860662);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 492
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 500
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, -148);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 50);

    ui_Image3 = lv_img_create(ui_Home);
    lv_img_set_src(ui_Image3, &ui_img_vitxmitatronics_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_Image3, 1);
    lv_obj_set_y(ui_Image3, -40);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_Button1, 259);
    lv_obj_set_height(ui_Button1, 52);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 84);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xE65062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label2, 232);
    lv_obj_set_height(ui_Label2, 29);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Select Recipe");
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Roboto_black_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi_menu = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_Wifi_menu, 156);
    lv_obj_set_height(ui_Wifi_menu, 114);
    lv_obj_set_x(ui_Wifi_menu, -500);
    lv_obj_set_y(ui_Wifi_menu, 112);
    lv_obj_set_align(ui_Wifi_menu, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Wifi_menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Wifi_menu);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "wifi menu...tbd");

    ui_Button10 = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_Button10, 47);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_x(ui_Button10, -364);
    lv_obj_set_y(ui_Button10, 205);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_img_create(ui_Button10);
    lv_img_set_src(ui_Image12, &ui_img_799859158);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_Image12, 241);
    lv_obj_set_y(ui_Image12, 241);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_zoom(ui_Image12, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToStatusChk = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_ToStatusChk, 98);
    lv_obj_set_height(ui_ToStatusChk, 54);
    lv_obj_set_x(ui_ToStatusChk, 343);
    lv_obj_set_y(ui_ToStatusChk, 203);
    lv_obj_set_align(ui_ToStatusChk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ToStatusChk, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ToStatusChk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ToStatusChk, lv_color_hex(0xE65062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ToStatusChk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_ToStatusChk);
    lv_obj_set_width(ui_Label16, 75);
    lv_obj_set_height(ui_Label16, 39);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Status Check");
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Roboto_condensed_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToStatusChk, ui_event_ToStatusChk, LV_EVENT_ALL, NULL);

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    ui_Home = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_Button1 = NULL;
    ui_Label2 = NULL;
    ui_Wifi_menu = NULL;
    ui_Label13 = NULL;
    ui_Button10 = NULL;
    ui_Image12 = NULL;
    ui_ToStatusChk = NULL;
    ui_Label16 = NULL;

}
